openapi: "3.0.1"
info:
  title: "Gracenote TV Guide"
  version: "1.0.0"
servers:
  - url: https://chatgpt.gntv.us
paths:
  /find_movies_near_me:
    get:
      operationId: find_movies_near_me
      summary: "Find movies showing near a particular zip code."
      parameters:
        - in: query
          name: zip
          schema:
            type: string
          required: true
          description: "The zip code to filter the movie data by."
      responses:
        "200":
          description: "Successful operation."
          content:
            application/json:
              schema:
                type: object
                properties:
                  source:
                    type: object
                    properties:
                      name:
                        type: string
                        description: "The name of the data source."
                    data:
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                            description: "Title of the movie."
                          description:
                            type: string
                            description: "Long-form description of the movie."
                          genre:
                            type: array
                            items:
                              type: string
                            description: "Genres associated with the movie."
                          topCast:
                            type: array
                            items:
                              type: string
                            description: "Top cast members of the movie."
                          preferredImageURI:
                            type: string
                            description: "URI of the preferred image for the movie."
        "400":
          description: "Bad request. Invalid parameters."
        "500":
          description: "Internal server error. Unable to fetch data from the external API."

